# Generated by Django 6.0.2 on 2026-02-25 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Vaqt'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Ro'yxatdan o'tgan"),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_active',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Oxirgi faollik'),
        ),
    ]
