# Generated by Django 6.0.2 on 2026-02-25 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_alter_message_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_messages', models.PositiveBigIntegerField(default=0, verbose_name='Jami murojaatlar')),
            ],
            options={
                'verbose_name': 'Tizim statistikasi',
                'verbose_name_plural': 'Tizim statistikasi',
            },
        ),
    ]
